language: android
jdk:
  - oraclejdk8
env:
  global:
    - GRADLE_OPTS="-Xms128m"
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24
    - extra-android-m2repository

script:
   - ./gradlew clean build
   - ./gradlew build jacocoTestReport

after_success: 
  - bash <(curl -s https://codecov.io/bash)
